# ansible m1 -m file -a "path=/home/ec2-user/new_dir state=directory"
---
- name: update m1 server
  hosts: m1

  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir
      state: directory
...
