# ansible m1 -m file -a "path=/home/ec2-user/new_dir state=directory"
---
- name: update m1 server
  hosts: m1 

  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir
      state: directory

  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_1
      state: directory

- name: update m1 server
  hosts: m2

  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_1
      state: directory

  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_2
      state: directory

- name: update gropu1 server
  hosts: g1

  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_group1
      state: directory

  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_group2
      state: directory      
...
