---
- name: Install HTTP server
  hosts: m4
  become: yes

  tasks:
  - name: Install Apache
    apt:
      name: apache
      state: present

  - name: start apache
    service:
      name: apache
      state: started

  - name: Enable apache
    service:
      name: apache
      enabled: yes
...

